# name: Create a release pull request

# on:
#   push:
#     branches:
#       - release/**
#       - hotfix/**
# jobs:
#   create-release-pr:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout source
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       - name: Set up Ruby 3.1
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: 3.1
#       - name: Setup vars
#         id: vars
#         run: |
#           echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"
#           echo "::set-output name=branch_prefix::$(echo ${GITHUB_REF} | cut -d '/' -f 3)"

#       - name: Creates a release pull request
#         env:
#           GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           GIT_PR_RELEASE_BRANCH_PRODUCTION: master
#           GIT_PR_RELEASE_BRANCH_STAGING: ${{ steps.vars.outputs.branch_name }}
#           GIT_PR_RELEASE_LABELS: ${{ steps.vars.outputs.branch_prefix }}
#           GIT_PR_RELEASE_TITLE: "[ReleasePR] ${{ steps.vars.outputs.branch_name }}"
#           GIT_PR_RELEASE_TEMPLATE: .github/git-pr-release-template.erb
#         run: |
#           gem install -N git-pr-release -v "1.9.0"
#           git-pr-release --no-fetch --squashed
