name: Create a release sheet pull request.
on:
  push:
    branches:
      - release/**
      - hotfix/**
jobs:
  create-release-sheet-pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BASE_BRANCH: master
    steps:
      - uses: actions/checkout@v2
      # リリース用PRが既に存在するかどうかをチェック
      - name: Check does pr exists
        id: check_is_release_pr_exist
        run: |
          echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"
          echo "::set-output name=body::$(git log --pretty=format:'- [ ] %h :%d %s (%an)' --abbrev-commit ${{ steps.vars.outputs.branch_name }}..master)"
      # リリース用PRを作成
      - name: Create release pr
        # if: ${{ steps.check_pr.outputs.count == 0 }}
        run: |
          gh pr create --base master --title "title" --body "${body}"
